version: "3"

services:
  ##########################################
  # Overrides for oada-core services:
  ##########################################

  # Add ourselves to admin container:
  admin:
    volumes:
      - ./services-available/oada-cron:/code/oada-cron
      - oada_cron_volume:/oada-cron


  ###############################################
  # This service's definition:
  ###############################################
  oada-cron:
    build:
      context: ./services-available/oada-cron
    container_name: oada-cron
    restart: always
    networks:
      - arango_net
    volumes:
      - ./services-available/oada-cron/daily:/etc/periodic/daily
      - ./services-available/oada-cron:/code/oada-cron
      - oada_cron_volume:/oada-cron
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/code/oada-srvc-docker
    command: crond -f -d 8

volumes:
  oada_cron_volume:
