#!/bin/sh

LOGFOLDER=/code/oada-cron/logs
LOG=${LOGFOLDER}/certbot.log

[ ! -e $LOGFOLDER ] && mkdir -p $LOGFOLDER

echo >> $LOG
echo "-------------------------------------" >> $LOG
date >> $LOG

echo "Attempting to renew certs..." >> $LOG
oada run --rm admin "certbot renew" >> $LOG 2>&1

echo "Done. Now restarting proxy..." >> $LOG
sleep 5 && oada restart proxy >> $LOG 2>&1

echo  "Done restarting proxy" >> $LOG
